name: Run Selenium Tests with Docker Grid

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Selenium Grid
        run: |
          docker-compose up -d
          sleep 10  

      - name: Run Tests
        run: |
          mvn clean test

      - name: Generate Allure Report
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.tgz
          tar -xvzf allure-2.30.0.tgz
          sudo mv allure-2.30.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure generate target/allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
